import type { PackageOffer } from './types';

export const recommendedPackages: PackageOffer[] = [
  {
    id: "EUR-PAR-01",
    title: "París: Amor y Luces",
    destination: "París, Francia",
    origin: "Bogotá",
    price: 1250,
    duration: 6,
    dates: "Octubre - Diciembre 2024",
    description: "Sumérgete en la ciudad del amor. Pasea por sus calles bohemias, admira el arte del Louvre y siente la magia de la Torre Eiffel iluminada por la noche.",
    includes: ["Vuelo redondo", "Hotel 4 estrellas céntrico", "Tour a la Torre Eiffel", "Crucero por el Sena", "Desayunos diarios"],
    not_included: ["Almuerzos y cenas", "Entradas a museos no especificados", "Gastos personales"],
    image: "https://images.unsplash.com/photo-1564227230898-87086d5b04dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxwYXJpcyUyMGVpZmZlbCUyMHRvd2VyfGVufDB8fHx8MTc1MjUxOTU5MHww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "paris eiffel tower",
    rating: 5,
    reviews: 1235,
    special_offer: "🔥 Oferta del Mes"
  },
  {
    id: "EUR-ROM-01",
    title: "Roma Eterna",
    destination: "Roma, Italia",
    origin: "Buenos Aires",
    price: 1480,
    duration: 7,
    dates: "Noviembre 2024 - Enero 2025",
    description: "Viaja en el tiempo y descubre los secretos del Imperio Romano. Lanza una moneda en la Fontana di Trevi, maravíllate con el Coliseo y disfruta de la mejor pasta.",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con desayuno", "Entrada al Coliseo y Foro Romano", "Clase de cocina italiana"],
    not_included: ["Impuesto turístico de la ciudad", "Propinas", "Almuerzos"],
    image: "https://images.unsplash.com/photo-1659003732403-fef512570038?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxyb21lJTIwY29sb3NzZXVtfGVufDB8fHx8MTc1MjUxOTU5MHww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "rome colosseum",
    rating: 5,
    reviews: 987
  },
  {
    id: "EUR-MAD-01",
    title: "Vibrante Madrid",
    destination: "Madrid, España",
    origin: "Ciudad de México",
    price: 1100,
    duration: 5,
    dates: "Septiembre - Noviembre 2024",
    description: "Vive la energía de la capital española. Recorre la Gran Vía, disfruta de un espectáculo de flamenco y saborea las mejores tapas en el Mercado de San Miguel.",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Gran Vía", "Tour de tapas y flamenco", "Entrada al Museo del Prado"],
    not_included: ["Bebidas en el show de flamenco", "Almuerzos y cenas", "Transporte local"],
    image: "https://images.unsplash.com/photo-1581206417531-8c377323620b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxtYWRyaWQlMjBncmFuJTIwdmlhfGVufDB8fHx8MTc1MjUxOTU5MHww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "madrid gran via",
    rating: 4,
    reviews: 1542
  },
  {
    id: "ASI-TYO-01",
    title: "Japón: Tradición y Futuro",
    destination: "Tokio, Japón",
    origin: "Medellín",
    price: 1950,
    duration: 8,
    dates: "Enero - Marzo 2025",
    description: "Descubre una ciudad de contrastes, donde templos milenarios conviven con rascacielos futuristas. Cruza el paso de peatones más concurrido del mundo y relájate en sus hermosos jardines.",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Shinjuku", "Visita al Templo Senso-ji", "Cruce de Shibuya", "Japan Rail Pass de 7 días"],
    not_included: ["Comidas", "Entradas a atracciones no especificadas", "Guía personal"],
    image: "https://images.unsplash.com/photo-1709654976353-2cc48d2b553a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHx0b2t5byUyMHNoaWJ1eWElMjBjcm9zc2luZ3xlbnwwfHx8fDE3NTI1MTk1OTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "tokyo shibuya crossing",
    rating: 5,
    reviews: 1890,
    special_offer: "🎌 Escapada a Japón"
  },
  {
    id: "AME-CUN-01",
    title: "Riviera Maya Total",
    destination: "Cancún, México",
    origin: "Bogotá",
    price: 850,
    duration: 5,
    dates: "Agosto - Octubre 2024",
    description: "Disfruta del sol, la arena y las aguas turquesas del Caribe. Explora antiguas ruinas mayas y nada en cenotes de aguas cristalinas. ¡El paraíso te espera!",
    includes: ["Vuelo redondo", "Resort 4 estrellas All-Inclusive", "Excursión a Chichén Itzá", "Snorkel en cenote"],
    not_included: ["Propinas", "Actividades acuáticas no especificadas", "Tasas de parque marino"],
    image: "https://images.unsplash.com/photo-1605581813258-076a6654a37f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxjYW5jdW4lMjBiZWFjaCUyMHJlc29ydHxlbnwwfHx8fDE3NTI1MTk1OTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "cancun beach resort",
    rating: 5,
    reviews: 2143
  },
  {
    id: "AME-NYC-01",
    title: "Descubre Nueva York",
    destination: "Nueva York, EE.UU.",
    origin: "Buenos Aires",
    price: 1300,
    duration: 6,
    dates: "Diciembre 2024 (Navidad)",
    description: "Siente la magia de la Navidad en la Gran Manzana. Patina sobre hielo en el Rockefeller Center, admira las luces de Times Square y pasea por un Central Park nevado.",
    includes: ["Vuelo redondo", "Hotel 4 estrellas cerca de Times Square", "Entrada al Empire State", "Paseo por Central Park"],
    not_included: ["Comidas", "Transporte en metro", "Entradas a espectáculos de Broadway"],
    image: "https://images.unsplash.com/photo-1454692173233-f4f34c12adad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxuZXclMjB5b3JrJTIwY2hyaXN0bWFzfGVufDB8fHx8MTc1MjUxOTU5MXww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "new york christmas",
    rating: 4,
    reviews: 1765,
    special_offer: "🎄 Navidad en NYC"
  },
];
