
export const recommendedPackages = [
  {
    id: "EUR-PAR-01",
    title: "París: Amor y Luces",
    destination: "París, Francia",
    origin: "Bogotá",
    price: 1250,
    duration: 6,
    dates: "Octubre - Diciembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas céntrico", "Tour a la Torre Eiffel", "Crucero por el Sena"],
    image: "https://images.unsplash.com/photo-1502602898657-3e91760c0341?fit=crop&w=1920&q=80",
    hint: "paris eiffel tower",
    rating: 5,
    reviews: 1235,
    special_offer: "🔥 Oferta del Mes"
  },
  {
    id: "EUR-ROM-01",
    title: "Roma Eterna",
    destination: "Roma, Italia",
    origin: "Buenos Aires",
    price: 1480,
    duration: 7,
    dates: "Noviembre 2024 - Enero 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con desayuno", "Entrada al Coliseo y Foro Romano", "Clase de cocina italiana"],
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?fit=crop&w=1920&q=80",
    hint: "rome colosseum",
    rating: 5,
    reviews: 987
  },
  {
    id: "EUR-MAD-01",
    title: "Vibrante Madrid",
    destination: "Madrid, España",
    origin: "Ciudad de México",
    price: 1100,
    duration: 5,
    dates: "Septiembre - Noviembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Gran Vía", "Tour de tapas y flamenco", "Entrada al Museo del Prado"],
    image: "https://images.unsplash.com/photo-1593967859232-5a21a9855598?fit=crop&w=1920&q=80",
    hint: "madrid gran via",
    rating: 4,
    reviews: 1542
  },
  {
    id: "ASI-TYO-01",
    title: "Japón: Tradición y Futuro",
    destination: "Tokio, Japón",
    origin: "Medellín",
    price: 1950,
    duration: 8,
    dates: "Enero - Marzo 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Shinjuku", "Visita al Templo Senso-ji", "Cruce de Shibuya"],
    image: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?fit=crop&w=1920&q=80",
    hint: "tokyo shibuya crossing",
    rating: 5,
    reviews: 1890,
    special_offer: "🎌 Escapada a Japón"
  },
  {
    id: "AME-CUN-01",
    title: "Riviera Maya Total",
    destination: "Cancún, México",
    origin: "Bogotá",
    price: 850,
    duration: 5,
    dates: "Agosto - Octubre 2024",
    includes: ["Vuelo redondo", "Resort 4 estrellas All-Inclusive", "Excursión a Chichén Itzá", "Snorkel en cenote"],
    image: "https://images.unsplash.com/photo-1580517595345-4293c4e675b3?fit=crop&w=1920&q=80",
    hint: "cancun beach resort",
    rating: 5,
    reviews: 2143
  },
  {
    id: "AME-NYC-01",
    title: "Descubre Nueva York",
    destination: "Nueva York, EE.UU.",
    origin: "Buenos Aires",
    price: 1300,
    duration: 6,
    dates: "Diciembre 2024 (Navidad)",
    includes: ["Vuelo redondo", "Hotel 4 estrellas cerca de Times Square", "Entrada al Empire State", "Paseo por Central Park"],
    image: "https://images.unsplash.com/photo-1533221332039-3ff70a59a997?fit=crop&w=1920&q=80",
    hint: "new york christmas",
    rating: 4,
    reviews: 1765,
    special_offer: "🎄 Navidad en NYC"
  },
  {
    id: "EUR-LON-01",
    title: "Londres Clásico",
    destination: "Londres, Reino Unido",
    origin: "Ciudad de México",
    price: 1400,
    duration: 7,
    dates: "Octubre - Diciembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Kensington", "Visita a la Torre de Londres", "Paseo en el London Eye"],
    image: "https://images.unsplash.com/photo-1529655683826-1c77ef053542?fit=crop&w=1920&q=80",
    hint: "london tower bridge",
    rating: 5,
    reviews: 1120
  },
  {
    id: "ASI-BKK-01",
    title: "Tesoros de Tailandia",
    destination: "Bangkok, Tailandia",
    origin: "Medellín",
    price: 1750,
    duration: 9,
    dates: "Febrero - Abril 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con piscina", "Tour de templos y Gran Palacio", "Mercados flotantes"],
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?fit=crop&w=1920&q=80",
    hint: "bangkok grand palace",
    rating: 5,
    reviews: 940
  },
   {
    id: "AME-CUZ-01",
    title: "Corazón Inca",
    destination: "Cusco, Perú",
    origin: "Bogotá",
    price: 980,
    duration: 5,
    dates: "Septiembre - Noviembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en centro histórico", "Tour a Machu Picchu en tren", "Visita al Valle Sagrado"],
    image: "https://images.unsplash.com/photo-1526481280643-335336f35423?fit=crop&w=1920&q=80",
    hint: "machu picchu peru",
    rating: 5,
    reviews: 2530,
    special_offer: "⛰️ Aventura Andina"
  },
  {
    id: "EUR-ATH-01",
    title: "Atenas y las Islas Griegas",
    destination: "Atenas, Grecia",
    origin: "Buenos Aires",
    price: 1850,
    duration: 8,
    dates: "Septiembre - Octubre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con vistas a la Acrópolis", "Ferry a Mykonos y Santorini"],
    image: "https://images.unsplash.com/photo-1586172355431-9957ce14b036?fit=crop&w=1920&q=80",
    hint: "santorini greece",
    rating: 5,
    reviews: 1340
  },
  {
    id: "AME-MIA-01",
    title: "Sol y Compras en Miami",
    destination: "Miami, EE.UU.",
    origin: "Medellín",
    price: 780,
    duration: 4,
    dates: "Agosto - Octubre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en South Beach", "Tour en hidrodeslizador por los Everglades"],
    image: "https://images.unsplash.com/photo-1533106418989-88406e768207?fit=crop&w=1920&q=80",
    hint: "miami south beach",
    rating: 4,
    reviews: 1980,
    special_offer: "☀️ Miami Express"
  },
  {
    id: "EUR-BCN-01",
    title: "Magia de Barcelona",
    destination: "Barcelona, España",
    origin: "Ciudad de México",
    price: 1150,
    duration: 6,
    dates: "Octubre - Diciembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas", "Entrada a la Sagrada Familia", "Paseo por el Barrio Gótico"],
    image: "https://images.unsplash.com/photo-1587789202104-a38b4a8e847c?fit=crop&w=1920&q=80",
    hint: "barcelona sagrada familia",
    rating: 5,
    reviews: 1620
  },
  {
    id: "ASI-SGP-01",
    title: "Singapur: Jardines del Futuro",
    destination: "Singapur",
    origin: "Bogotá",
    price: 2100,
    duration: 7,
    dates: "Enero - Marzo 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con piscina infinita", "Entrada a Gardens by the Bay", "Safari Nocturno"],
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?fit=crop&w=1920&q=80",
    hint: "singapore gardens by the bay",
    rating: 5,
    reviews: 1150
  },
  {
    id: "AME-BUE-01",
    title: "Pasión Porteña",
    destination: "Buenos Aires, Argentina",
    origin: "Bogotá",
    price: 890,
    duration: 5,
    dates: "Noviembre 2024 - Enero 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Palermo", "Cena con show de tango", "Tour por Caminito"],
    image: "https://images.unsplash.com/photo-1618544703566-52c50a049d5e?fit=crop&w=1920&q=80",
    hint: "buenos aires la boca",
    rating: 4,
    reviews: 1430
  },
  {
    id: "EUR-IST-01",
    title: "Estambul: Dos Mundos",
    destination: "Estambul, Turquía",
    origin: "Buenos Aires",
    price: 1650,
    duration: 7,
    dates: "Septiembre - Noviembre 2024",
    includes: ["Vuelo redondo", "Hotel boutique 4 estrellas", "Visita a Santa Sofía y Mezquita Azul", "Paseo en barco por el Bósforo"],
    image: "https://images.unsplash.com/photo-1581358597332-9f1c5040fb98?fit=crop&w=1920&q=80",
    hint: "istanbul hagia sophia",
    rating: 5,
    reviews: 880
  },
  {
    id: "ASI-DPS-01",
    title: "Bali Espiritual",
    destination: "Bali, Indonesia",
    origin: "Ciudad de México",
    price: 1990,
    duration: 9,
    dates: "Octubre - Diciembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas con yoga", "Visita a terrazas de arroz de Tegalalang", "Templo de Uluwatu"],
    image: "https://images.unsplash.com/photo-1537953773345-d172ccfa13c0?fit=crop&w=1920&q=80",
    hint: "bali rice terraces",
    rating: 5,
    reviews: 1950,
     special_offer: "🌴 Paraíso Bali"
  },
  {
    id: "AME-LAS-01",
    title: "Las Vegas Espectacular",
    destination: "Las Vegas, EE.UU.",
    origin: "Medellín",
    price: 950,
    duration: 4,
    dates: "Septiembre - Noviembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en el Strip", "Entradas para un show del Cirque du Soleil", "Excursión al Gran Cañón"],
    image: "https://images.unsplash.com/photo-1605833552951-812674246a48?fit=crop&w=1920&q=80",
    hint: "las vegas strip",
    rating: 4,
    reviews: 2200
  },
  {
    id: "EUR-PRG-01",
    title: "Praga de Cuento de Hadas",
    destination: "Praga, República Checa",
    origin: "Bogotá",
    price: 1350,
    duration: 6,
    dates: "Noviembre 2024 - Enero 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas", "Tour del Castillo de Praga", "Paseo por el Puente de Carlos"],
    image: "https://images.unsplash.com/photo-1596701062351-8c2c14d9fdd0?fit=crop&w=1920&q=80",
    hint: "prague charles bridge",
    rating: 5,
    reviews: 995
  },
  {
    id: "AME-RIO-01",
    title: "Carnaval en Río",
    destination: "Río de Janeiro, Brasil",
    origin: "Buenos Aires",
    price: 1100,
    duration: 5,
    dates: "Febrero 2025",
    includes: ["Vuelo redondo", "Hotel 4 estrellas en Copacabana", "Entrada al Sambódromo", "Visita al Cristo Redentor"],
    image: "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?fit=crop&w=1920&q=80",
    hint: "rio de janeiro carnival",
    rating: 5,
    reviews: 2800,
    special_offer: "🎉 Carnaval 2025"
  },
  {
    id: "ASI-DXB-01",
    title: "Dubai del Futuro",
    destination: "Dubai, EAU",
    origin: "Ciudad de México",
    price: 1800,
    duration: 6,
    dates: "Octubre - Diciembre 2024",
    includes: ["Vuelo redondo", "Hotel 4 estrellas", "Subida al Burj Khalifa", "Safari por el desierto en 4x4"],
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?fit=crop&w=1920&q=80",
    hint: "dubai skyline",
    rating: 5,
    reviews: 1750
  }
]
