
import type { PackageOffer } from './types';

export const recommendedPackages: PackageOffer[] = [
  {
    id: "EUR-PAR-01",
    title: "Parisian Romance",
    destination: "Paris, France",
    origin: "New York",
    price: 1250,
    duration: 6,
    dates: "October - December 2024",
    description: "Immerse yourself in the charm and history of the City of Light. Stroll along the Seine, visit world-class museums, and enjoy the vibrant nightlife.",
    includes: ["Round-trip flight", "4-star hotel in Le Marais", "Eiffel Tower Summit Access", "Daily breakfasts"],
    not_included: ["Lunches and dinners", "Museum tickets", "Personal expenses"],
    image: "https://images.unsplash.com/photo-1522093007474-d86e9bf7ba6f?w=500",
    hint: "paris eiffel tower",
    rating: 5,
    reviews: 2150,
    special_offer: "🔥 Monthly Special"
  },
  {
    id: "ASIA-TYO-01",
    title: "Tokyo Neon & Tradition",
    destination: "Tokyo, Japan",
    origin: "London",
    price: 1880,
    duration: 7,
    dates: "November 2024 - January 2025",
    description: "Discover the heart of Japan where ancient tradition meets futuristic technology. Stay in a modern hotel, explore temples, and get lost in the bustling streets of Shibuya.",
    includes: ["Flight to Tokyo", "Boutique hotel in Shinjuku", "Sushi making class", "Day trip to Mt. Fuji"],
    not_included: ["Ground transportation", "Lunches and dinners", "Gratuities"],
    image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=500",
    hint: "tokyo japan temple",
    rating: 5,
    reviews: 1987,
  },
  {
    id: "AFR-SRG-01",
    title: "Serengeti Wildlife Safari",
    destination: "Serengeti, Tanzania",
    origin: "Frankfurt",
    price: 3200,
    duration: 8,
    dates: "September - November 2024",
    description: "Experience a unique adventure in the heart of Africa. Witness the Great Migration, meet local communities, and see exotic wildlife in its natural habitat.",
    includes: ["Flight to Kilimanjaro", "Lodge accommodation in the Serengeti", "All meals", "Guided game drives"],
    not_included: ["Alcoholic beverages", "Travel insurance", "Park entrance fees"],
    image: "https://images.unsplash.com/photo-1566884239546-e58a8806cb5c?w=500",
    hint: "serengeti safari tanzania",
    rating: 5,
    reviews: 1542
  },
  {
    id: "EUR-AMF-01",
    title: "Amalfi Coast Dream",
    destination: "Amalfi Coast, Italy",
    origin: "New York",
    price: 1620,
    duration: 5,
    dates: "January - March 2025",
    description: "A trip to a surreal landscape where the mountains meet the sea. Stay in a cliffside hotel and discover the local culture in Positano and Ravello.",
    includes: ["Flight to Naples", "Private transfers", "Boutique hotel with sea view", "Typical meals", "Visit to Positano and Ravello"],
    not_included: ["Beverages", "Gratuities", "Personal insurance"],
    image: "https://images.unsplash.com/photo-1621758448353-9bcf7b4da2f9?w=500",
    hint: "amalfi coast italy",
    rating: 5,
    reviews: 1890,
    special_offer: "🍋 Amalfi Adventure"
  },
  {
    id: "SA-RIO-01",
    title: "Rio Carnival Experience",
    destination: "Rio de Janeiro, Brazil",
    origin: "Miami",
    price: 1450,
    duration: 5,
    dates: "February 2025",
    description: "Experience the world's most famous carnival. A perfect mix of beach relaxation and vibrant parades.",
    includes: ["Flight to Rio", "4-star hotel in Copacabana", "Sambadrome parade tickets", "Daily breakfasts"],
    not_included: ["Meals", "Personal expenses"],
    image: "https://images.unsplash.com/photo-1708716174800-978f0f2762ae?w=500",
    hint: "rio de janeiro brazil",
    rating: 5,
    reviews: 2143
  },
  {
    id: "CAR-MAL-01",
    title: "Maldives Overwater Paradise",
    destination: "Maldives",
    origin: "Dubai",
    price: 2890,
    duration: 6,
    dates: "December 2024",
    description: "Discover a sea of infinite colors. Enjoy the beaches and escape to the tranquility and pristine beauty of an overwater bungalow.",
    includes: ["Flight to Malé", "Seaplane transfer", "Overwater bungalow", "All-inclusive plan", "Snorkeling tour"],
    not_included: ["Tourism tax", "Premium beverages", "Scuba diving"],
    image: "https://images.unsplash.com/photo-1592782985575-a96c6e647155?w=500",
    hint: "maldives overwater bungalow",
    rating: 5,
    reviews: 1765,
    special_offer: "🌊 Paradise Getaway"
  }
];

    