import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import RootLayout from './layout'; // Adjust the import path if necessary

describe('RootLayout', () => {
  it('should render correctly with children', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    expect(screen.getByText('Test Child')).toBeInTheDocument();
  });

  it('should have the correct metadata (title and description)', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    expect(document.title).toBe('Create Next App'); // Assuming this is the default title
    const descriptionMeta = document.querySelector('meta[name="description"]');
    expect(descriptionMeta).toHaveAttribute('content', 'Generated by create next app'); // Assuming this is the default description
  });

  it('should include the correct font preconnect and href links', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    const preconnectLink = document.querySelector('link[rel="preconnect"]');
    expect(preconnectLink).toHaveAttribute('href', 'https://fonts.googleapis.com');

    const fontHrefLink = document.querySelector('link[href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap"]');
    expect(fontHrefLink).toBeInTheDocument();
  });

  it('should include the correct favicon link', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    const faviconLink = document.querySelector('link[rel="icon"]');
    expect(faviconLink).toHaveAttribute('href', '/favicon.ico');
  });

  it('should render the Toaster component', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    // This test assumes the Toaster component renders a specific element or attribute
    // You may need to adjust this based on the actual Toaster implementation
    const toasterElement = screen.getByTestId('toaster'); // Assuming a data-testid="toaster" on the Toaster component
    expect(toasterElement).toBeInTheDocument();
  });

  it('should render the Footer component', () => {
    render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    // This test assumes the Footer component renders a specific element or attribute
    // You may need to adjust this based on the actual Footer implementation
    const footerElement = screen.getByRole('contentinfo'); // Assuming the Footer uses the contentinfo role
    expect(footerElement).toBeInTheDocument();
  });
});